# Generated by Django 4.0.4 on 2022-05-10 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doktori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=50)),
                ('prezime', models.CharField(max_length=50)),
                ('telefon', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('titula', models.CharField(max_length=50)),
                ('oddelenie', models.CharField(max_length=50)),
                ('specijalizacija', models.CharField(max_length=50)),
                ('faksimil', models.IntegerField(unique=True)),
                ('godini_iskustvo', models.IntegerField()),
                ('plata', models.IntegerField()),
                ('rakovoditel', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Oddeli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=50)),
                ('kapacitet', models.IntegerField()),
                ('broj_pomoshen_personal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pacienti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=50)),
                ('prezime', models.CharField(max_length=50)),
                ('telefon', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('data_ragjanje', models.DateField()),
                ('embg', models.CharField(max_length=50, unique=True)),
                ('pol', models.CharField(max_length=50)),
                ('krvodaritel', models.BooleanField()),
                ('krvna_grupa', models.CharField(max_length=50)),
                ('osiguran', models.BooleanField()),
                ('hronichni_bolesti', models.BooleanField()),
                ('hronichni_zabeleshka', models.TextField(blank=True, null=True)),
                ('alergii', models.BooleanField()),
                ('alergii_zabeleshka', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pregledi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_pregled', models.DateTimeField()),
                ('zabeleshka', models.CharField(max_length=50, null=True)),
                ('kontrola', models.IntegerField(blank=True, null=True)),
                ('dijagnoza', models.TextField()),
                ('terapija', models.TextField(blank=True, null=True)),
                ('doktor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.doktori')),
                ('oddelenie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.oddeli')),
                ('pacient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.pacienti')),
            ],
        ),
        migrations.CreateModel(
            name='Hospitalizacija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('dijagnoza', models.CharField(max_length=50)),
                ('rezultati', models.TextField(blank=True, null=True)),
                ('broj_soba', models.IntegerField()),
                ('broj_krevet', models.IntegerField()),
                ('terapija', models.TextField(blank=True, null=True)),
                ('momentalno_hospitaliziran', models.BooleanField()),
                ('oddel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.oddeli')),
                ('pacient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.pacienti')),
            ],
        ),
    ]
