# Generated by Django 4.0.4 on 2022-05-11 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalizacija',
            name='oddel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.oddeli'),
        ),
        migrations.AlterField(
            model_name='hospitalizacija',
            name='pacient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.pacienti'),
        ),
        migrations.AlterField(
            model_name='pregledi',
            name='doktor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.doktori'),
        ),
        migrations.AlterField(
            model_name='pregledi',
            name='oddelenie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.oddeli'),
        ),
        migrations.AlterField(
            model_name='pregledi',
            name='pacient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.pacienti'),
        ),
        migrations.CreateModel(
            name='Upat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termin', models.DateTimeField()),
                ('zabeleshka', models.TextField()),
                ('prioritet', models.BooleanField(default=False)),
                ('doktor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.doktori')),
                ('oddelenie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.oddeli')),
                ('pacient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.pacienti')),
            ],
        ),
        migrations.AddField(
            model_name='pregledi',
            name='termin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.upat'),
        ),
    ]
