# Generated by Django 4.0.4 on 2022-05-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_upat_termin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upat',
            name='termin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
